spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false
  redis:
    host: localhost
    port: 6379
    timeout: 5000

app:
  idempotency:
    ttl-seconds: 600 # 10 minutes
    lock-timeout: 10 # 10 seconds
  cache:
    balance-ttl-seconds: 300 # 5 min
    historical-balance-ttl-seconds: 86400 # 24 hours
    wallet-ttl-seconds: 300 # 5 min

