spring:
  datasource:
    url: jdbc:postgresql://ws_database:5432/walletdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false
  redis:
    host: redis
    port: 6379
    timeout: 5000