version: '3.8'

services:
  wallet_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wallet_service
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      ws_database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  ws_database:
    image: postgres:17
    container_name: ws_database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d walletdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
