global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'wallet-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080', 'wallet-service:8080']
